server:
  port: 20003
spring:
  application:
    name: @artifactId@
  #数据源配置
  datasource:
    url: ${mate.datasource.url}
    username: ${mate.datasource.username}
    password: ${mate.datasource.password}
  cloud:
    nacos:
      config:
        server-addr: 172.18.252.95:8848
      discovery:
        server-addr: 172.18.252.95:8848