server:
  port: 30001
spring:
  application:
    name: @artifactId@
  boot:
    admin:
      ui:
        title: @artifactId@-server
      client:
        instance:
          metadata:
            tags:
              environment: local
      notify:
        dingding:
          enabled: false
          token: AA***************BB
  security:
    user:
      name: admin
      password: matecloud
  cloud:
    nacos:
      config:
        server-addr: 172.18.252.95:8848
      discovery:
        server-addr: 172.18.252.95:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always