server:
  port: 10001
spring:
  cache:
    type: redis
  redis:
    host: 172.18.252.95
    port: 6379
    database: 0
    password:
    #密码（默认为空）
    ssl: false
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
  data:
    redis:
      #redis 单机环境配置
      host: 172.18.252.95
      port: 6379
      password:
      database: 0
      ssl: false
  application:
    name: @artifactId@
  cloud:
    gateway:
      discovery:

        locator:

          enabled: true

    loadbalancer:

      nacos:
        enabled: true
      cache:
        enabled: true
        ttl: 5
      retry:
        enabled: true
        max-retries-on-same-service-instance: 1
        max-retries-on-next-service-instance: 2
        retry-on-all-operations: true
      health-check:
        refetch-instances-interval: 5
    nacos:
      config:
        server-addr: 172.18.252.95:8848
        config-long-poll-timeout: 10

      discovery:
        server-addr: 172.18.252.95:8848
        watch-delay: 10000

#        metadata:
#          preserved.heart.beat.interval: 1 #心跳间隔。时间单位:秒。心跳间隔
#          preserved.heart.beat.timeout: 3 #心跳暂停。时间单位:秒。 即服务端6秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
#          preserved.ip.delete.timeout: 6 #Ip删除超时。时间单位:秒。即服务端9秒收不到客户端心跳，会将该客户端注册的实例删除：
#        heart-beat-interval: 1
#        heart-beat-timeout: 3
#        ip-delete-timeout: 6

mate:
  #自定义路径配置
  route:
    config:
      data-id: mate-gateway-router
      group: DEFAULT_GROUP
  #MateRequestProperties属性配置
  request:
    #traceId跟踪
    trace: true
    #获取IP
    ip: true
    #黑名单增强模式启动
    enhance: true
logging:
  level:
    root: debug
