server:
  port: 20001
spring:
  redis:
    host: 172.18.252.95
    port: 6379
    database: 0
    password:
    #密码（默认为空）
    ssl: false
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）
  data:
    redis:
      #redis 单机环境配置
      host: 172.18.252.95
      port: 6379
      password:
      database: 0
      ssl: false
  application:
    name: @artifactId@
  #数据源配置
  datasource:
    url: ${mate.datasource.url}
    username: ${mate.datasource.username}
    password: ${mate.datasource.password}
  cloud:
    nacos:
      config:
        server-addr: 172.18.252.95:8848
      discovery:
        server-addr: 172.18.252.95:8848

dubbo:
  registry:
    #   The Spring Cloud Dubbo's registry extension
    ##  the default value of dubbo-provider-services is "*", that means to subscribe all providers,
    ##  thus it's optimized if subscriber specifies the required providers.
    address: spring-cloud://localhost
#    address: nacos://127.0.0.1:8848
  #   The traditional Dubbo's registry also is supported
  #   address: zookeeper://127.0.0.1:2181
  cloud:
    # The subscribed services in consumer side
    subscribed-services: ${provider.application.name}
  consumer:
    check: false

provider:
  application:
    name: mate-system

justauth:
  enabled: true
  type:
    github:
      client-id: 75a51afd3b0a2fc32952
      client-secret: dcf425ac89******************736d2317b
      redirect-uri: http://localhost:10001/mate-uaa/auth/callback/github
    wechat_open:
      client-id: wxdcb******4ff4
      client-secret: b4e9dc************************a08ed6d
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat/callback
    QQ:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/qq/callback
      union-id: false
  cache:
    type: redis
    prefix: 'SOCIAL::STATE::'
    timeout: 1h
social:
  vue:
    url: http://localhost:9528/#/socialcallback
## 配置日志显示在spring boot admin
logging:
  file:
    name: logs/app/mate-uaa/mate-uaa.log

  level:
    root: error